spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beadhousedb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  type-aliases-package: com.ctbu.entity
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    call-setters-on-nulls: true